### ISSUE TITLE
Distributing the patched source code?

### ISSUE THREAD

**Issue by cpitclaudel** [astyonax/patched-RTS5227-5229#4]
Thanks for this patch.  Since the Realtek drivers are GPL, it would be totally fine to redistribute a patched version, instead of just the patch. Maybe it would be simpler to do that? :)

```
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
```

(Keeping a copy of the patch would be nice, of course, since it allows to easily check what you changed; but for most people being able to download the patched code would be even better, I think).

**Comment by astyonax** [comment]
You are right! I didn't check the license of the drivers indeed.
I'll update the repo with the drivers and the new instructions!
